
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"J:\Python programming file\test gui e-wallet\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("430x932")
window.configure(bg = "#EFEDED")


canvas = Canvas(
    window,
    bg = "#EFEDED",
    height = 932,
    width = 430,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    430.0,
    103.93881225585938,
    fill="#AF52DE",
    outline="")

canvas.create_text(
    142.25048828125,
    61.71942138671875,
    anchor="nw",
    text="Transfer Funds",
    fill="#FFFFFF",
    font=("Inter SemiBold", 20 * -1)
)


canvas.create_rectangle(
    29.0,
    58.71942138671875,
    54.0,
    83.71942138671875,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    383.0068359375,
    60.21942138671875,
    408.0068359375,
    85.21942138671875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    50.0,
    249.28907775878906,
    380.0,
    364.64674377441406,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    50.0,
    197.87509155273438,
    250.0,
    223.58209228515625,
    fill="#F0EDED",
    outline="")

canvas.create_text(
    29.5703125,
    199.72857666015625,
    anchor="nw",
    text="Send to another Ewallet account",
    fill="#6E2A91",
    font=("Inter ExtraBold", 16 * -1)
)

canvas.create_rectangle(
    79.0,
    276.0,
    144.0,
    341.0,
    fill="#000000",
    outline="")

canvas.create_text(
    171.394287109375,
    289.54168701171875,
    anchor="nw",
    text="Transfer",
    fill="#5C0986",
    font=("Inter ExtraBold", 24 * -1)
)

canvas.create_text(
    174.394287109375,
    319.0,
    anchor="nw",
    text="Send E-wallet",
    fill="#A98AB9",
    font=("Inter ExtraBold", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
