
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"J:\Python programming file\test gui e-wallet\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("430x932")
window.configure(bg = "#EFEDED")


canvas = Canvas(
    window,
    bg = "#EFEDED",
    height = 932,
    width = 430,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    430.0,
    103.93881225585938,
    fill="#AF52DE",
    outline="")

canvas.create_text(
    142.25048828125,
    61.71942138671875,
    anchor="nw",
    text="Transfer Funds",
    fill="#FFFFFF",
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_rectangle(
    121.9931640625,
    153.0,
    136.9931640625,
    168.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    29.0,
    58.71942138671875,
    54.0,
    83.71942138671875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    383.0068359375,
    60.21942138671875,
    408.0068359375,
    85.21942138671875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    50.25048828125,
    175.31268310546875,
    380.25048828125,
    303.3210906982422,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    130.0,
    175.31268310546875,
    130.17301017045975,
    303.98779296875,
    fill="#000000",
    outline="")

canvas.create_text(
    148.522216796875,
    228.65023803710938,
    anchor="nw",
    text="Enter name or number",
    fill="#C1AFAF",
    font=("Inter SemiBold", 17 * -1)
)

canvas.create_rectangle(
    150.0,
    230.76235961914062,
    150.0,
    248.21103858947754,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    66.0,
    214.65023803710938,
    116.0,
    264.6502380371094,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    153.25048828125,
    315.0,
    193.25048828125,
    355.0,
    fill="#000000",
    outline="")

canvas.create_text(
    200.0,
    324.0,
    anchor="nw",
    text="Scan QR",
    fill="#4A086B",
    font=("Inter SemiBold", 17 * -1)
)
window.resizable(False, False)
window.mainloop()
