
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"J:\Python programming file\test gui e-wallet\build\assets\frame6")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("430x932")
window.configure(bg = "#F0EDED")


canvas = Canvas(
    window,
    bg = "#F0EDED",
    height = 932,
    width = 430,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    17.719589233398438,
    356.39495849609375,
    110.91600036621094,
    433.37965393066406,
    fill="#F0EDED",
    outline="")

canvas.create_rectangle(
    174.33929443359375,
    356.39495849609375,
    267.53570556640625,
    433.37965393066406,
    fill="#F0EDED",
    outline="")

canvas.create_rectangle(
    316.25146484375,
    356.1807861328125,
    409.4478759765625,
    433.1654815673828,
    fill="#F0EDED",
    outline="")

canvas.create_rectangle(
    29.135528564453125,
    147.18917846679688,
    399.1355285644531,
    321.59442138671875,
    fill="#B063D7",
    outline="")

canvas.create_text(
    156.0,
    185.55242919921875,
    anchor="nw",
    text="Available Balance",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    89.5,
    208.57489013671875,
    anchor="nw",
    text="PHP 900,000.00",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_rectangle(
    143.24685668945312,
    264.033935546875,
    285.02418518066406,
    299.3053741455078,
    fill="#A210EB",
    outline="")

canvas.create_text(
    200.0,
    269.6696472167969,
    anchor="nw",
    text="Cash in",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_rectangle(
    165.7935028076172,
    271.83966064453125,
    186.6100845336914,
    291.4996795654297,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    205.0,
    364.66546630859375,
    245.0,
    404.66546630859375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    339.84967041015625,
    364.66546630859375,
    379.84967041015625,
    404.66546630859375,
    fill="#000000",
    outline="")

canvas.create_text(
    22.916000366210938,
    418.16546630859375,
    anchor="nw",
    text="Transfer Funds",
    fill="#B063D7",
    font=("Inter SemiBold", 12 * -1)
)

canvas.create_text(
    185.0,
    415.16546630859375,
    anchor="nw",
    text="Bills Payment",
    fill="#B063D7",
    font=("Inter SemiBold", 12 * -1)
)

canvas.create_text(
    339.84967041015625,
    415.16546630859375,
    anchor="nw",
    text="ESavings",
    fill="#B063D7",
    font=("Inter SemiBold", 12 * -1)
)

canvas.create_rectangle(
    0.0,
    862.4881591796875,
    430.0,
    931.9999389648438,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    40.33447265625,
    870.02734375,
    80.33447265625,
    910.02734375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    181.8901824951172,
    826.759033203125,
    248.10980987548828,
    895.9217529296875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    196.93585205078125,
    842.4136962890625,
    233.0641098022461,
    880.2671203613281,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    344.22735595703125,
    869.9999389648438,
    384.22735595703125,
    909.9999389648438,
    fill="#000000",
    outline="")

canvas.create_text(
    40.23388671875,
    906.0,
    anchor="nw",
    text="Home",
    fill="#57087E",
    font=("Inter SemiBold", 14 * -1)
)

canvas.create_text(
    176.4524688720703,
    899.02734375,
    anchor="nw",
    text="QR Scanner",
    fill="#B063D7",
    font=("Inter SemiBold", 14 * -1)
)

canvas.create_text(
    330.22735595703125,
    909.9999389648438,
    anchor="nw",
    text="My profile",
    fill="#B063D7",
    font=("Inter SemiBold", 14 * -1)
)

canvas.create_rectangle(
    127.70649719238281,
    65.96017456054688,
    184.2935028076172,
    122.54718017578125,
    fill="#000000",
    outline="")

canvas.create_text(
    190.36793518066406,
    87.91119384765625,
    anchor="nw",
    text="Ewallet",
    fill="#A210EB",
    font=("LeagueSpartan Bold", 32 * -1)
)

canvas.create_text(
    192.0,
    906.0,
    anchor="nw",
    text=" ",
    fill="#000000",
    font=("LeagueSpartan Bold", 32 * -1)
)

canvas.create_text(
    164.0,
    483.9268493652344,
    anchor="nw",
    text="View All Services",
    fill="#A210EB",
    font=("Inter Bold", 14 * -1)
)

canvas.create_rectangle(
    205.0,
    471.26953125,
    236.875,
    477.89453125,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    38.4375,
    556.473876953125,
    403.4375,
    771.473876953125,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    48.0,
    364.66546630859375,
    94.0,
    410.66546630859375,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
