
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"J:\Python programming file\test gui e-wallet\build\assets\frame5")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("430x932")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 932,
    width = 430,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    430.0,
    507.3915710449219,
    fill="#A860CD",
    outline="")

canvas.create_rectangle(
    30.278045654296875,
    548.3668823242188,
    91.34314727783203,
    589.5858001708984,
    fill="#FFFEFE",
    outline="")

canvas.create_rectangle(
    30.278076171875,
    650.2549438476562,
    91.34317779541016,
    691.4738616943359,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    30.278076171875,
    748.556640625,
    91.34317779541016,
    789.7755584716797,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    184.46746826171875,
    748.556640625,
    245.5325698852539,
    789.7755584716797,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    184.46746826171875,
    838.8096313476562,
    245.5325698852539,
    880.0285491943359,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    30.0,
    890.1153564453125,
    150.0,
    917.6837615966797,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    55.81060791015625,
    558.0,
    anchor="nw",
    text="1",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_rectangle(
    280.0,
    890.1153564453125,
    399.99967193603516,
    917.6837615966797,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    338.9349060058594,
    748.556640625,
    400.00000762939453,
    789.7755584716797,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    184.46746826171875,
    548.3668823242188,
    245.5325698852539,
    589.5858001708984,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    341.0619812011719,
    548.3668823242188,
    402.12708282470703,
    589.5858001708984,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    209.40530395507812,
    556.976318359375,
    anchor="nw",
    text="2",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_rectangle(
    184.46746826171875,
    650.2549438476562,
    245.5325698852539,
    691.4738616943359,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    338.9349060058594,
    548.3668823242188,
    400.00000762939453,
    589.5858001708984,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    338.9349060058594,
    650.2549438476562,
    400.00000762939453,
    691.4738616943359,
    fill="#FFFCFC",
    outline="")

canvas.create_text(
    363.59454345703125,
    558.0,
    anchor="nw",
    text="3",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    53.81060791015625,
    658.0,
    anchor="nw",
    text="4",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    209.40530395507812,
    658.0,
    anchor="nw",
    text="5",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    363.59454345703125,
    658.8643798828125,
    anchor="nw",
    text="6",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    54.81060791015625,
    757.1660766601562,
    anchor="nw",
    text="7",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    208.40530395507812,
    757.1660766601562,
    anchor="nw",
    text="8",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    364.39141845703125,
    757.1660766601562,
    anchor="nw",
    text="9",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    209.40530395507812,
    846.8585205078125,
    anchor="nw",
    text="0",
    fill="#A860CD",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    54.81060791015625,
    895.8995361328125,
    anchor="nw",
    text="Help Center",
    fill="#A860CD",
    font=("Inter Bold", 13 * -1)
)

canvas.create_text(
    303.0457458496094,
    895.8995361328125,
    anchor="nw",
    text="Forgot EPIN?",
    fill="#A860CD",
    font=("Inter Bold", 13 * -1)
)

canvas.create_rectangle(
    336.228515625,
    149.181884765625,
    447.5712127685547,
    173.5476131439209,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    65.81060791015625,
    480.26953125,
    363.59454345703125,
    493.26953887939453,
    fill="#A860CD",
    outline="")

canvas.create_text(
    115.40530395507812,
    480.26953125,
    anchor="nw",
    text="Never share your EPIN with anyone. ",
    fill="#DCD6D6",
    font=("Inter Bold", 11 * -1)
)

canvas.create_rectangle(
    100.0,
    361.048583984375,
    330.0,
    405.71665954589844,
    fill="#8504C6",
    outline="")

canvas.create_text(
    136.52984619140625,
    374.7688903808594,
    anchor="nw",
    text="+63-1234567890",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_rectangle(
    287.97906494140625,
    386.0420227050781,
    304.5710639953613,
    394.1491746902466,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    290.08349609375,
    377.1168518066406,
    306.6755027770996,
    385.2240037918091,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    130.0,
    256.114013671875,
    300.0,
    314.0357666015625,
    fill="#A860CD",
    outline="")

canvas.create_text(
    154.0,
    260.5439453125,
    anchor="nw",
    text="Enter your EPIN",
    fill="#FFFFFF",
    font=("Inter Bold", 16 * -1)
)

canvas.create_rectangle(
    163.35980224609375,
    289.5357666015625,
    189.35980224609375,
    315.5357666015625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    248.34814453125,
    295.5357666015625,
    262.34814453125,
    309.5357666015625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    216.52813720703125,
    289.5357666015625,
    242.52813720703125,
    315.5357666015625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    195.17979431152344,
    295.5357666015625,
    209.17979431152344,
    309.5357666015625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    102.5572509765625,
    105.32464599609375,
    180.99999237060547,
    184.76739501953125,
    fill="#000000",
    outline="")

canvas.create_text(
    184.42572021484375,
    128.31903076171875,
    anchor="nw",
    text="Ewallet",
    fill="#FFFFFF",
    font=("LeagueSpartan Bold", 40 * -1)
)

canvas.create_rectangle(
    312.42572021484375,
    39.48260498046875,
    541.1441955566406,
    177.06890869140625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    83.5042724609375,
    48.7894287109375,
    326.78173828125,
    216.904541015625,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
